flags: {}
nix:
  packages:
  - ncurses
packages:
- '.'
extra-deps:
- QuickCheck-2.9.1
- regex-base-0.93.2
- regex-tdfa-rc-1.1.8.3
- tasty-0.11.0.2
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- tf-random-0.5
- unbounded-delays-0.1.0.9
resolver: ghc-8.0
